# Chapter 16 Examples

In [38]:
# %load ../EXAMPLES/np_create_arrays.py
#!/usr/bin/env python
import numpy as np

a = np.array([[1, 2.1, 3], [4, 5, 6], [7, 8, 9], [20, 30, 40]])  # <1>
print(a)
print("# dims", a.ndim)  # <2>
print("shape", a.shape)  # <3>
print()

a_zeros = np.zeros((3, 5), dtype=np.uint32)  # <4>
print(a_zeros)
print()

a_ones = np.ones((2, 3, 4, 5))  # <5>
print(a_ones)
print()

# with uninitialized values
a_empty = np.empty((3, 8))  # <6>
print(a_empty)

print(a.dtype)  # <7>

nan_array = np.full((5, 10), np.NaN)  # <8>
print(nan_array)


[[ 1.   2.1  3. ]
 [ 4.   5.   6. ]
 [ 7.   8.   9. ]
 [20.  30.  40. ]]
# dims 2
shape (4, 3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]

[[ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000  0.00000000e+000  0.00000000e+000  2.16334242e-314]
 [ 3.10503618e+231  3.10503618e+231  5.92878775e-323  0.00000000e+000
   0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 3.10503618e+231  3.10503618e+231 -3.95252517e-323  0.00000000e+000
   2.12199579e-

In [39]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [20, 30, 40]]) 
a


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [20, 30, 40]])

In [40]:
a[0], a[1], a[-1]

(array([1, 2, 3]), array([4, 5, 6]), array([20, 30, 40]))

In [41]:
print(a.ndim, a.shape)

2 (4, 3)


In [42]:
a_zeros = np.zeros((3, 5, 10), dtype=np.uint32)  # <4>
a_zeros

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=uint32)

In [43]:
print(a_zeros.shape)

(3, 5, 10)


In [44]:
a_ones = np.ones((4, 4))

In [45]:
a_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
a_un = np.empty((10, 2))
a_un

array([[3.10503618e+231, 3.10503618e+231],
       [6.91691904e-323, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [3.10503618e+231, 3.10503618e+231],
       [3.10503618e+231, 3.10503618e+231],
       [3.10503618e+231, 3.10503618e+231]])

In [47]:
nan_array = np.full((3,3,3), np.NaN)
nan_array

array([[[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]]])

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# np.arange(START, STOP, STEP)  np.arange(STOP) np.arange(START,STOP)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.arange(1,2.1, .1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [51]:
np.linspace(1, 50, 5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [52]:
np.linspace(1, 10, 200)

array([ 1.        ,  1.04522613,  1.09045226,  1.13567839,  1.18090452,
        1.22613065,  1.27135678,  1.31658291,  1.36180905,  1.40703518,
        1.45226131,  1.49748744,  1.54271357,  1.5879397 ,  1.63316583,
        1.67839196,  1.72361809,  1.76884422,  1.81407035,  1.85929648,
        1.90452261,  1.94974874,  1.99497487,  2.04020101,  2.08542714,
        2.13065327,  2.1758794 ,  2.22110553,  2.26633166,  2.31155779,
        2.35678392,  2.40201005,  2.44723618,  2.49246231,  2.53768844,
        2.58291457,  2.6281407 ,  2.67336683,  2.71859296,  2.7638191 ,
        2.80904523,  2.85427136,  2.89949749,  2.94472362,  2.98994975,
        3.03517588,  3.08040201,  3.12562814,  3.17085427,  3.2160804 ,
        3.26130653,  3.30653266,  3.35175879,  3.39698492,  3.44221106,
        3.48743719,  3.53266332,  3.57788945,  3.62311558,  3.66834171,
        3.71356784,  3.75879397,  3.8040201 ,  3.84924623,  3.89447236,
        3.93969849,  3.98492462,  4.03015075,  4.07537688,  4.12

In [53]:
# %load ../EXAMPLES/np_basic_array_ops.py
#!/usr/bin/env python
import numpy as np

a = np.array(
    [
        [5, 10, 15],
        [2, 4, 6],
        [3, 6, 9, ],
    ]
)  # <1>

b = np.array(
    [
        [10, 85, 92],
        [77, 16, 14],
        [19, 52, 23],
    ]
)  # <2>
print("a")
print(a)
print()
print("b")
print(b)
print()

print("a * 10")
print(a * 10)  # <3>
print()

print("a + b")
print(a + b)  # <4>
print()

print("b + 3")
print(b + 3)  # <5>
print()

s1 = a.sum()  # <6>
s2 = b.sum()  # <6>
print("sum of a is {0}; sum of b is {1}".format(s1, s2))
print()

a += 1000  # <7>
print(a)


a
[[ 5 10 15]
 [ 2  4  6]
 [ 3  6  9]]

b
[[10 85 92]
 [77 16 14]
 [19 52 23]]

a * 10
[[ 50 100 150]
 [ 20  40  60]
 [ 30  60  90]]

a + b
[[ 15  95 107]
 [ 79  20  20]
 [ 22  58  32]]

b + 3
[[13 88 95]
 [80 19 17]
 [22 55 26]]

sum of a is 60; sum of b is 388

[[1005 1010 1015]
 [1002 1004 1006]
 [1003 1006 1009]]


In [54]:
a

array([[1005, 1010, 1015],
       [1002, 1004, 1006],
       [1003, 1006, 1009]])

In [55]:
b

array([[10, 85, 92],
       [77, 16, 14],
       [19, 52, 23]])

In [56]:
a + b

array([[1015, 1095, 1107],
       [1079, 1020, 1020],
       [1022, 1058, 1032]])

In [57]:
a @ b

array([[107105, 154365, 129945],
       [106442, 153546, 129378],
       [106663, 153819, 129567]])

In [58]:
a * b

array([[10050, 85850, 93380],
       [77154, 16064, 14084],
       [19057, 52312, 23207]])

In [59]:
a + 1
a

array([[1005, 1010, 1015],
       [1002, 1004, 1006],
       [1003, 1006, 1009]])

In [60]:
a += 1
a

array([[1006, 1011, 1016],
       [1003, 1005, 1007],
       [1004, 1007, 1010]])

In [62]:
a

array([[1006, 1011, 1016],
       [1003, 1005, 1007],
       [1004, 1007, 1010]])

In [63]:
a.sum()

9069

In [64]:
a[0].sum()

3033

In [65]:
a.shape

(3, 3)

In [66]:
b.shape

(3, 3)

In [67]:
x = np.ones((4, 10))

In [68]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [69]:
x.size

40

In [70]:
x.ndim

2

In [71]:
x.shape = 10, 4
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
a

array([[1006, 1011, 1016],
       [1003, 1005, 1007],
       [1004, 1007, 1010]])

In [73]:
a.transpose()

array([[1006, 1003, 1004],
       [1011, 1005, 1007],
       [1016, 1007, 1010]])

In [74]:
a.ravel()

array([1006, 1011, 1016, 1003, 1005, 1007, 1004, 1007, 1010])

In [75]:
np.linalg.inv(a)

array([[ 4.49496715e+12,  8.98993429e+12, -1.34849014e+13],
       [-8.98993429e+12, -1.79798686e+13,  2.69698029e+13],
       [ 4.49496715e+12,  8.98993429e+12, -1.34849014e+13]])

In [102]:
# %load ../EXAMPLES/np_indexing.py
#!/usr/bin/env python
import numpy as np

a = np.array(
    [[70, 31, 21, 76, 19, 5, 54, 66],
     [23, 29, 71, 12, 27, 74, 65, 73],
     [11, 84, 7, 10, 31, 50, 11, 98],
     [25, 13, 43, 1, 31, 52, 41, 90],
     [75, 37, 11, 62, 35, 76, 38, 4]]
)  # <1>

print(a)
print()

print('a[0] =>', a[0])  # <2>
print('a[0][0] =>', a[0][0])  # <3>
print('a[0,0] =>', a[0, 0])  # <4>
print('a[0,:3] =>', a[0, :3])  # <5>
print('a[0,::2] =>', a[0, ::2])  # <6>
print()
print('a[::2] =>', a[::2])  # <7>
print()
print('a[:3, -2:] =>', a[:3, -2:])  # <8>


[[70 31 21 76 19  5 54 66]
 [23 29 71 12 27 74 65 73]
 [11 84  7 10 31 50 11 98]
 [25 13 43  1 31 52 41 90]
 [75 37 11 62 35 76 38  4]]

a[0] => [70 31 21 76 19  5 54 66]
a[0][0] => 70
a[0,0] => 70
a[0,:3] => [70 31 21]
a[0,::2] => [70 21 19 54]

a[::2] => [[70 31 21 76 19  5 54 66]
 [11 84  7 10 31 50 11 98]
 [75 37 11 62 35 76 38  4]]

a[:3, -2:] => [[54 66]
 [65 73]
 [11 98]]


In [78]:
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73],
       [11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90],
       [75, 37, 11, 62, 35, 76, 38,  4]])

In [79]:
a[0]

array([70, 31, 21, 76, 19,  5, 54, 66])

In [80]:
a[0][0], a[0,0]

(70, 70)

In [81]:
a[-1,-1]

4

In [82]:
a[0,:3]

array([70, 31, 21])

In [83]:
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73],
       [11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90],
       [75, 37, 11, 62, 35, 76, 38,  4]])

In [84]:
a[a,:3]

array([70, 31, 21])

In [86]:
a[:,0]

array([70, 23, 11, 25, 75])

In [87]:
a[:,:2]

array([[70, 31],
       [23, 29],
       [11, 84],
       [25, 13],
       [75, 37]])

In [90]:
big_array = np.ones((10000000,2))
big_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [91]:
big_array.size

20000000

In [92]:
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73],
       [11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90],
       [75, 37, 11, 62, 35, 76, 38,  4]])

In [94]:
#  ARRAY[row-or-row-slize, col-or-col-slice]
a[:3,-3:]

array([[ 5, 54, 66],
       [74, 65, 73],
       [50, 11, 98]])

In [95]:
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73],
       [11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90],
       [75, 37, 11, 62, 35, 76, 38,  4]])

In [96]:
a > 70

array([[False, False, False,  True, False, False, False, False],
       [False, False,  True, False, False,  True, False,  True],
       [False,  True, False, False, False, False, False,  True],
       [False, False, False, False, False, False, False,  True],
       [ True, False, False, False, False,  True, False, False]])

In [97]:
a == 76

array([[False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False, False]])

In [98]:
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73],
       [11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90],
       [75, 37, 11, 62, 35, 76, 38,  4]])

In [99]:
a[a > 70] *= 100
a

array([[  70,   31,   21, 7600,   19,    5,   54,   66],
       [  23,   29, 7100,   12,   27, 7400,   65, 7300],
       [  11, 8400,    7,   10,   31,   50,   11, 9800],
       [  25,   13,   43,    1,   31,   52,   41, 9000],
       [7500,   37,   11,   62,   35, 7600,   38,    4]])

In [100]:
i = a > 70
i

array([[False, False, False,  True, False, False, False, False],
       [False, False,  True, False, False,  True, False,  True],
       [False,  True, False, False, False, False, False,  True],
       [False, False, False, False, False, False, False,  True],
       [ True, False, False, False, False,  True, False, False]])

In [101]:
a[i]

array([7600, 7100, 7400, 7300, 8400, 9800, 9000, 7500, 7600])

In [103]:
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73],
       [11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90],
       [75, 37, 11, 62, 35, 76, 38,  4]])

In [104]:
a[i]

array([76, 71, 74, 73, 84, 98, 90, 75, 76])

In [ ]:
# %load ../EXAMPLES/np_stacking.py
#!/usr/bin/env python
import numpy as np

a = np.array(
    [[70, 31, 21, 76, 19, 5, 54, 66],
     [23, 29, 71, 12, 27, 74, 65, 73]]
)  # <1>

b = np.array(
    [[11, 84, 7, 10, 31, 50, 11, 98],
     [25, 13, 43, 1, 31, 52, 41, 90]]
)  # <2>

print('a =>\n', a)
print()
print('b =>\n', b)
print()
print('vstack((a,b)) =>\n', np.vstack((a, b)))  # <3>
print()

print('vstack((a,a[0] + a[1])) =>\n', np.vstack((a, a[0] + a[1])))  # <4>
print()

print('hstack((a,b)) =>\n', np.hstack((a, b)))  # <5>


In [106]:
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73],
       [11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90],
       [75, 37, 11, 62, 35, 76, 38,  4]])

In [107]:
b

array([[10, 85, 92],
       [77, 16, 14],
       [19, 52, 23]])

In [108]:
a = np.array(
    [[70, 31, 21, 76, 19, 5, 54, 66],
     [23, 29, 71, 12, 27, 74, 65, 73]]
)  # <1>

b = np.array(
    [[11, 84, 7, 10, 31, 50, 11, 98],
     [25, 13, 43, 1, 31, 52, 41, 90]]
)  # <2

In [109]:
a

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73]])

In [110]:
b

array([[11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90]])

In [113]:
np.vstack((a, b))

array([[70, 31, 21, 76, 19,  5, 54, 66],
       [23, 29, 71, 12, 27, 74, 65, 73],
       [11, 84,  7, 10, 31, 50, 11, 98],
       [25, 13, 43,  1, 31, 52, 41, 90]])

In [114]:
np.hstack((a, b))

array([[70, 31, 21, 76, 19,  5, 54, 66, 11, 84,  7, 10, 31, 50, 11, 98],
       [23, 29, 71, 12, 27, 74, 65, 73, 25, 13, 43,  1, 31, 52, 41, 90]])

In [117]:
for value in a.flat:  # or a.flatten()
    print(value)

70
31
21
76
19
5
54
66
23
29
71
12
27
74
65
73


In [130]:
x = np.full((5, 3), 42.)
x

array([[42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.]])

In [131]:
print(x.size, x.ndim, x.shape, x.dtype)

15 2 (5, 3) float64
